# Import libraries

In [18]:
import os
from PIL import Image
from matplotlib import pyplot
import numpy as np
import cv2
from mtcnn.mtcnn import MTCNN
import tensorflow as tf   
tf.get_logger().setLevel('ERROR')

# Create function that extracts faces

In [19]:
# def extract_face_mtcnn(filepath):
#     print(filepath)
#     required_size = (160, 160)
#     image = Image.open(filepath)
#     image = image.convert('RGB')
#     image_pixels = np.asarray(image)
#     detector = MTCNN()
#     result = detector.detect_faces(image_pixels)
#     if len(result) == 0:
#         return "no face"
#     x1, y1, width, height = result[0]['box']
#     x1, y1 = abs(x1), abs(y1)
#     x2, y2 = x1 + width, y1 + height
#     face = image_pixels[y1:y2, x1:x2]
    
#     image = Image.fromarray(face)
#     image = image.resize(required_size)
#     face_array = np.asarray(image)
#     return face_array
def extract_face_haarcascade(filepath):
    required_size = (160, 160)
    face_cascade = cv2.CascadeClassifier('../haarcascade_frontalface_default.xml')
    
    print(filepath)
    img = cv2.imread(filepath)
    image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    pixels = np.asarray(image)
    
    face = face_cascade.detectMultiScale(image, 1.1, 4)
    if len(face) == 0:
        return 'no face'
    print(face)
    face = face[0]
    x1, y1, width, height = face
    x1, y1 = abs(x1), abs(y1)
    x2, y2 = x1 + width, y1+height
    face = pixels[y1:y2, x1:x2]
    image = Image.fromarray(face)
    
    image = image.resize(required_size)
    face_array = np.asarray(image)
    return face_array

# Create function that loads all images from a subdirectory

In [20]:
def load_faces(directory):
#     print("in load_faces")
    faces = list()
    for filename in os.listdir(directory):
        path = directory + filename
        # get face
        face = extract_face_haarcascade(path)
        if faces == "no face":
            return False
        # store face
        faces.append(face)
    return faces

# Create functions that loads the entire dataset

In [21]:
def load_dataset(directory):
#     print("in load_dataset")
    X, y = list(), list()
    # enumerate folders, on per class
    for subdir in os.listdir(directory):
        # path
        path = directory + subdir + '/'
        # skip any files that might be in the dir
        if not os.path.isdir(path):
            continue
        # load all faces in the subdirectory
        faces = load_faces(path)
        if not faces:
            return 
        # create labels
        labels = [subdir for _ in range(len(faces))]
        # summarize progress
        print('>loaded %d examples for class: %s' % (len(faces), subdir))
        # store
        X.extend(faces)
        y.extend(labels)
    return np.asarray(X), np.asarray(y)

# save compressed file

In [22]:
X, y = load_dataset('../data/new-data/')

print(X.shape, y.shape)

# save arrays to one file in compressed format
np.savez_compressed('../data/haarcascade-faces-dataset.npz', X, y)

../data/new-data/Ann Achadang/DSC_0055.JPG
[[286  65 145 145]
 [514 393 103 103]]
../data/new-data/Ann Achadang/DSC_0056.JPG
../data/new-data/Ann Achadang/DSC_0057.JPG
[[ 19 299  41  41]]
../data/new-data/Ann Achadang/DSC_0084.JPG
[[242 121 160 160]]
>loaded 4 examples for class: Ann Achadang
../data/new-data/Ben Wycliff Mugalu/ben.jpg
../data/new-data/Ben Wycliff Mugalu/FB_IMG_15887865661953252.jpg
../data/new-data/Ben Wycliff Mugalu/FB_IMG_15887865743369205.jpg
[[347 103 131 131]]
../data/new-data/Ben Wycliff Mugalu/IMG_20200319_191417_128.jpg
[[255   9 211 211]]
../data/new-data/Ben Wycliff Mugalu/IMG_20200319_191438_356.jpg
[[180  90 205 205]]
../data/new-data/Ben Wycliff Mugalu/IMG_20200506_203820_898.jpg
[[ 56 131 222 222]]
../data/new-data/Ben Wycliff Mugalu/IMG_20200506_204256_646.jpg
[[263 191 238 238]]
../data/new-data/Ben Wycliff Mugalu/IMG_20200506_204331_377.jpg
[[272  99 188 188]]
>loaded 8 examples for class: Ben Wycliff Mugalu
../data/new-data/Brenda Chemashak/DSC_0072.

[[ 909 1382  753  753]
 [2916 2418   50   50]]
../data/new-data/Linda Nabatte/IMG_20200529_130012.jpg
[[ 985 1386  823  823]
 [1986 1859   64   64]
 [ 238 2606   57   57]
 [ 281 2930   94   94]
 [2554 3444  526  526]
 [2417 3600   62   62]
 [ 556 3679   68   68]]
../data/new-data/Linda Nabatte/IMG_20200529_130018.jpg
[[1103 1419  664  664]
 [1264 2287   55   55]
 [1976 3721  103  103]
 [ 397 4003   95   95]
 [1758 4106   33   33]]
../data/new-data/Linda Nabatte/IMG_20200529_130026.jpg
[[ 988 1137  801  801]]
../data/new-data/Linda Nabatte/IMG_20200529_130031.jpg
[[ 830  873  924  924]
 [1310 2570   59   59]
 [  67 3028   56   56]
 [  91 3086   49   49]
 [  35 3364   30   30]]
>loaded 8 examples for class: Linda Nabatte
../data/new-data/Liz Nakandi/DSC_0081.JPG
[[261 155 114 114]]
../data/new-data/Liz Nakandi/DSC_0082.JPG
[[230 153 120 120]]
../data/new-data/Liz Nakandi/DSC_0083.JPG
[[339 112 117 117]]
../data/new-data/Liz Nakandi/IMG_20200529_130149.jpg
[[ 985  865  863  863]
 [1128 29

[[2356  173   30   30]
 [2462  141   42   42]
 [2606   49   65   65]
 [1888  399  354  354]
 [1157  222   78   78]
 [1306   39   77   77]
 [ 169   37  140  140]
 [2712  554   86   86]
 [  57  581   88   88]
 [2586  929   60   60]
 [2500 1136   47   47]
 [1028 1238   42   42]
 [ 288 1592   95   95]]
../data/new-data/Reagan Daniel Ogaba/DSC_0124.JPG
[[1474   69   65   65]
 [2446  399   57   57]
 [ 886  542  106  106]
 [ 585  733  166  166]
 [1481 1693   45   45]
 [2552 1897   51   51]]
>loaded 5 examples for class: Reagan Daniel Ogaba
../data/new-data/Titus Weikama/IMG-20200525-WA0002.jpg
[[303 329 197 197]]
../data/new-data/Titus Weikama/IMG-20200525-WA0004.jpg
[[132 284 301 301]]
../data/new-data/Titus Weikama/IMG-20200525-WA0005.jpg
[[120 285 334 334]]
../data/new-data/Titus Weikama/IMG-20200525-WA0006.jpg
[[143 281 291 291]]
../data/new-data/Titus Weikama/IMG-20200525-WA0007.jpg
[[222 293 298 298]]
../data/new-data/Titus Weikama/IMG-20200525-WA0008.jpg
[[120 301 344 344]]
../data/new

/home/ben/.local/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
